version: "3.8"

services:

# ********************************************************************
# MongoDB. NoSQL database
# ********************************************************************
  mongo:
    image: mongo:8.0.0-rc13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: GhjcnjGfhjkm12
    ports:
      - 27017:27017
    volumes:
      - ./init_db/:/docker-entrypoint-initdb.d/:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: GhjcnjGfhjkm12
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:GhjcnjGfhjkm12@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

# ********************************************************************
# Приложение с fastapi внутри контейнера
# ********************************************************************
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "8008:8008"
    depends_on:
      - mongo
    volumes:
      - ./app:/mac-finder/app
      - ./static:/mac-finder/static
    command: uvicorn app.__main__:app_loader --host=0.0.0.0 --port 8008 --reload

